[env:nrf52840dk]
platform = platformio/nordicnrf52@10.9.0
board = nrf52840_dk
framework = zephyr
board_build.zephyr.variant = nrf52840dk/nrf52840
board_build.zephyr.cmake_extra_args = -DCONF_FILE=${PROJECT_DIR}/prj.conf -DDTC_OVERLAY_FILE=app.overlay
platform_packages =
    framework-zephyr@3.40200.0
