//! ESP32-S2 Companion for Wake-on-LAN proxy
//! 
//! This program runs on an ESP32-S2 microcontroller and provides an alternative
//! wake method by emulating USB mouse movement when receiving UDP wake commands.

use anyhow::Result;
use log::*;
use serde::{Deserialize, Serialize};
use std::{
    net::UdpSocket,
    sync::{Arc, Mutex},
    thread,
    time::Duration,
};

// Include the embedded configuration generated by build.rs
include!(concat!(env!("OUT_DIR"), "/embedded_config.rs"));

/// Configuration structure for the ESP32-S2 companion
#[derive(Debug, Deserialize, Serialize)]
pub struct Config {
    pub wifi: WifiConfig,
    pub wake: WakeConfig,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct WifiConfig {
    pub ssid: String,
    pub password: String,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct WakeConfig {
    pub udp_port: u16,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            wifi: WifiConfig {
                ssid: "".to_string(),
                password: "".to_string(),
            },
            wake: WakeConfig {
                udp_port: 9999,
            },
        }
    }
}

/// Load configuration from embedded build-time constants
pub fn load_config() -> Result<Config> {
    let embedded = get_embedded_config();
    
    info!("Loading embedded configuration");
    
    let config = Config {
        wifi: WifiConfig {
            ssid: embedded.wifi_ssid.to_string(),
            password: embedded.wifi_password.to_string(),
        },
        wake: WakeConfig {
            udp_port: embedded.udp_port,
        },
    };
    
    if config.wifi.ssid.is_empty() {
        warn!("Wi-Fi SSID is empty in embedded config");
    } else {
        info!("Loaded embedded configuration with SSID: {}", config.wifi.ssid);
    }
    
    Ok(config)
}

/// Connect to Wi-Fi using the provided configuration
#[cfg(target_os = "espidf")]
fn connect_wifi(config: &WifiConfig) -> Result<()> {
    use embedded_svc::wifi::{ClientConfiguration, Configuration, Wifi};
    use esp_idf_svc::{
        eventloop::EspSystemEventLoop,
        hal::prelude::Peripherals,
        wifi::{BlockingWifi, EspWifi},
        netif::EspNetifWait,
    };

    let peripherals = Peripherals::take()?;
    let sys_loop = EspSystemEventLoop::take()?;
    let nvs = esp_idf_svc::nvs::EspDefaultNvsPartition::take()?;

    let mut wifi = BlockingWifi::wrap(
        EspWifi::new(peripherals.modem, sys_loop.clone(), Some(nvs))?,
        sys_loop,
    )?;

    let wifi_configuration = Configuration::Client(ClientConfiguration {
        ssid: config.ssid.as_str().into(),
        password: config.password.as_str().into(),
        ..Default::default()
    });

    wifi.set_configuration(&wifi_configuration)?;
    wifi.start()?;
    info!("Starting Wi-Fi...");

    wifi.connect()?;
    info!("Connecting to Wi-Fi...");

    wifi.wait_netif_up()?;
    info!("Wi-Fi connected!");

    let ip_info = wifi.wifi().sta_netif().get_ip_info()?;
    info!("IP info: {:?}", ip_info);

    Ok(())
}

/// Mock Wi-Fi connection for non-ESP32 platforms
#[cfg(not(target_os = "espidf"))]
fn connect_wifi(config: &WifiConfig) -> Result<()> {
    info!("Mock Wi-Fi connection to SSID: {}", config.ssid);
    Ok(())
}

/// Emulate mouse movement to wake the connected computer
pub fn wake_computer() -> Result<()> {
    info!("Performing mouse wake gesture...");
    
    #[cfg(target_os = "espidf")]
    {
        use esp_idf_hal::usb::UsbOtg;
        use usbd_hid::descriptor::{MouseReport, SerializedDescriptor};
        
        // Initialize USB HID mouse for ESP32-S2
        info!("Initializing USB HID mouse on ESP32-S2");
        
        // Create a small mouse movement to wake the computer
        // Move cursor 1 pixel right, then 1 pixel left to return to original position
        let move_right = MouseReport {
            x: 1,
            y: 0,
            buttons: 0,
            wheel: 0,
            pan: 0,
        };
        
        let move_left = MouseReport {
            x: -1,
            y: 0,
            buttons: 0,
            wheel: 0,
            pan: 0,
        };
        
        // This is a simplified implementation
        // In a full implementation, you would:
        // 1. Set up USB peripheral
        // 2. Configure HID device
        // 3. Send the mouse reports
        // 4. Handle USB events properly
        
        info!("Sending mouse movement reports...");
        
        // Simulate sending the reports
        // send_mouse_report(&move_right)?;
        thread::sleep(Duration::from_millis(10));
        // send_mouse_report(&move_left)?;
        
        info!("USB HID mouse movement completed");
    }
    
    #[cfg(not(target_os = "espidf"))]
    {
        info!("Mock mouse movement: move right 1px, then left 1px");
        thread::sleep(Duration::from_millis(20)); // Simulate the time it takes
    }
    
    Ok(())
}

#[cfg(target_os = "espidf")]
/// Send a mouse report via USB HID (ESP32-S2 implementation)
fn send_mouse_report(report: &usbd_hid::descriptor::MouseReport) -> Result<()> {
    // This would be the actual USB HID implementation for ESP32-S2
    // For now, it's a placeholder that logs the action
    info!("Sending mouse report: x={}, y={}", report.x, report.y);
    Ok(())
}

/// UDP server that listens for wake commands
pub fn udp_server(port: u16, wake_requested: Arc<Mutex<bool>>) -> Result<()> {
    let socket = UdpSocket::bind(format!("0.0.0.0:{}", port))?;
    socket.set_read_timeout(Some(Duration::from_secs(1)))?;
    
    info!("UDP server listening on port {}", port);
    
    let mut buf = [0; 64];
    
    loop {
        match socket.recv_from(&mut buf) {
            Ok((size, src)) => {
                info!("Received {} bytes from {}", size, src);
                
                // Simple wake command - any UDP packet triggers wake
                // In production, you might want to verify the packet content
                let mut wake_flag = wake_requested.lock().unwrap();
                *wake_flag = true;
                info!("Wake requested from {}", src);
            }
            Err(e) if e.kind() == std::io::ErrorKind::WouldBlock => {
                // Timeout, continue loop
                continue;
            }
            Err(e) => {
                warn!("UDP receive error: {}", e);
                thread::sleep(Duration::from_secs(1));
            }
        }
    }
}

fn main() -> Result<()> {
    // Initialize the logger
    #[cfg(target_os = "espidf")]
    {
        esp_idf_sys::link_patches();
        esp_idf_svc::log::EspLogger::initialize_default();
    }
    
    #[cfg(not(target_os = "espidf"))]
    {
        env_logger::init();
    }

    info!("ESP32-S2 Companion starting...");

    // Load embedded configuration
    let config = load_config()?;
    
    // Check if Wi-Fi credentials are configured
    if config.wifi.ssid.is_empty() {
        error!("Wi-Fi SSID not configured!");
        error!("Please ensure config.json has Wi-Fi credentials before building (see config.json.example)");
        return Err(anyhow::anyhow!("Wi-Fi not configured in embedded config"));
    }

    // Connect to Wi-Fi
    connect_wifi(&config.wifi)?;

    // Shared flag to signal wake requests
    let wake_requested = Arc::new(Mutex::new(false));
    let wake_requested_clone = wake_requested.clone();

    // Start UDP server in a separate thread
    let udp_port = config.wake.udp_port;
    thread::spawn(move || {
        if let Err(e) = udp_server(udp_port, wake_requested_clone) {
            error!("UDP server error: {}", e);
        }
    });

    info!("ESP32-S2 Companion ready!");
    info!("Listening for wake commands on UDP port {}", config.wake.udp_port);

    // Main loop - check for wake requests and execute them
    loop {
        {
            let mut wake_flag = wake_requested.lock().unwrap();
            if *wake_flag {
                if let Err(e) = wake_computer() {
                    error!("Failed to wake computer: {}", e);
                } else {
                    info!("Computer wake completed");
                }
                *wake_flag = false;
            }
        }
        
        thread::sleep(Duration::from_millis(100));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_config_default() {
        let config = Config::default();
        assert_eq!(config.wake.udp_port, 9999);
        assert!(config.wifi.ssid.is_empty());
    }

    #[test]
    fn test_config_serialization() {
        let config = Config {
            wifi: WifiConfig {
                ssid: "test_ssid".to_string(),
                password: "test_password".to_string(),
            },
            wake: WakeConfig {
                udp_port: 8888,
            },
        };
        
        let json = serde_json::to_string(&config).unwrap();
        let parsed: Config = serde_json::from_str(&json).unwrap();
        
        assert_eq!(parsed.wifi.ssid, "test_ssid");
        assert_eq!(parsed.wifi.password, "test_password");
        assert_eq!(parsed.wake.udp_port, 8888);
    }

    #[test]
    fn test_wake_computer_placeholder() {
        // Test that the wake function doesn't panic
        let result = wake_computer();
        assert!(result.is_ok());
    }

    #[test]
    fn test_load_config_embedded() {
        // Test loading embedded config
        let config = load_config().unwrap();
        assert!(config.wake.udp_port > 0); // Should have a valid port
    }
}