// Build script for ESP32 companion
// Reads config.json and embeds it as compile-time constants

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=config.json");
    
    // Read config.json and generate embedded configuration
    generate_embedded_config();
}

fn generate_embedded_config() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("embedded_config.rs");
    
    // Try to read config.json
    let config_content = match fs::read_to_string("config.json") {
        Ok(content) => content,
        Err(_) => {
            // If config.json doesn't exist, use config.json.example or defaults
            match fs::read_to_string("config.json.example") {
                Ok(content) => {
                    eprintln!("Warning: config.json not found, using config.json.example");
                    content
                },
                Err(_) => {
                    eprintln!("Warning: Neither config.json nor config.json.example found, using defaults");
                    r#"{
    "wifi": {
        "ssid": "",
        "password": ""
    },
    "wake": {
        "udp_port": 9999
    }
}"#.to_string()
                }
            }
        }
    };
    
    // Parse the JSON to extract values
    match parse_and_generate_config(&config_content, &dest_path) {
        Ok(_) => println!("Generated embedded configuration"),
        Err(e) => {
            eprintln!("Error generating config: {}", e);
            std::process::exit(1);
        }
    }
}

fn parse_and_generate_config(json_content: &str, dest_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    // Remove JSON comments (lines starting with //)
    let cleaned_content: String = json_content
        .lines()
        .filter(|line| !line.trim().starts_with("//"))
        .collect::<Vec<&str>>()
        .join("\n");
    
    // Parse JSON manually to avoid dependencies in build.rs
    let config: serde_json::Value = serde_json::from_str(&cleaned_content)?;
    
    let wifi_ssid = config["wifi"]["ssid"].as_str().unwrap_or("");
    let wifi_password = config["wifi"]["password"].as_str().unwrap_or("");
    let udp_port = config["wake"]["udp_port"].as_u64().unwrap_or(9999) as u16;
    
    let generated_code = format!(
        r#"// Generated embedded configuration from config.json
// DO NOT EDIT - This file is automatically generated by build.rs

/// Embedded Wi-Fi SSID
pub const WIFI_SSID: &str = "{}";

/// Embedded Wi-Fi password  
pub const WIFI_PASSWORD: &str = "{}";

/// Embedded UDP port for wake commands
pub const UDP_PORT: u16 = {};

/// Embedded configuration structure
pub struct EmbeddedConfig {{
    pub wifi_ssid: &'static str,
    pub wifi_password: &'static str,
    pub udp_port: u16,
}}

impl EmbeddedConfig {{
    pub const fn new() -> Self {{
        Self {{
            wifi_ssid: WIFI_SSID,
            wifi_password: WIFI_PASSWORD,
            udp_port: UDP_PORT,
        }}
    }}
}}

/// Get the embedded configuration
pub const fn get_embedded_config() -> EmbeddedConfig {{
    EmbeddedConfig::new()
}}
"#,
        wifi_ssid.replace("\\", "\\\\").replace("\"", "\\\""),
        wifi_password.replace("\\", "\\\\").replace("\"", "\\\""),
        udp_port
    );
    
    fs::write(dest_path, generated_code)?;
    Ok(())
}