/*
 * Copyright (c) 2024 WOL Proxy Project
 *
 * SPDX-License-Identifier: MIT
 */

#pragma once

/*
 * CHIP project configuration for nRF52840 WOL Companion
 */

// Device identification
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID 0xFFF1
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID 0x8000
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION 1
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING "1.0"
#define CHIP_DEVICE_CONFIG_DEVICE_HARDWARE_VERSION 1
#define CHIP_DEVICE_CONFIG_DEVICE_HARDWARE_VERSION_STRING "1.0"

// Device type - Switch device (0x000F)
#define CHIP_DEVICE_CONFIG_DEVICE_TYPE 0x000F

// Enable Button cluster support
#define CHIP_DEVICE_CONFIG_ENABLE_BUTTON_CLUSTER 1

// Commissioning settings
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 12345678
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR 3840

// Security settings
#define CHIP_DEVICE_CONFIG_ENABLE_THREAD_SRP_CLIENT 1
#define CHIP_DEVICE_CONFIG_ENABLE_THREAD_DNS_CLIENT 1

// Network settings
#define CHIP_DEVICE_CONFIG_ENABLE_WIFI 0
#define CHIP_DEVICE_CONFIG_ENABLE_THREAD 1
#define CHIP_DEVICE_CONFIG_ENABLE_ETHERNET 0

// Storage settings
#define CHIP_DEVICE_CONFIG_ENABLE_CHIP_TIME_SERVICE_TIME_SYNC 0

// OTA settings
#define CHIP_DEVICE_CONFIG_ENABLE_OTA_REQUESTOR 0

// Reduce memory usage for constrained device
#define CHIP_DEVICE_CONFIG_MAX_EVENT_SIZE 512
#define CHIP_DEVICE_CONFIG_EVENT_LOGGING_UTC_TIMESTAMPS 0