/*
 * Copyright (c) 2024 WOL Proxy Project
 *
 * SPDX-License-Identifier: MIT
 */

#pragma once

/*
 * OpenThread configuration for Matter on nRF52840 WOL Companion
 */

// Thread network settings for Matter
#define OPENTHREAD_CONFIG_THREAD_VERSION OT_THREAD_VERSION_1_3
#define OPENTHREAD_CONFIG_COMMISSIONER_ENABLE 1
#define OPENTHREAD_CONFIG_JOINER_ENABLE 1
#define OPENTHREAD_CONFIG_DHCP6_CLIENT_ENABLE 1
#define OPENTHREAD_CONFIG_DHCP6_SERVER_ENABLE 1
#define OPENTHREAD_CONFIG_DNS_CLIENT_ENABLE 1
#define OPENTHREAD_CONFIG_SRP_CLIENT_ENABLE 1
#define OPENTHREAD_CONFIG_SRP_SERVER_ENABLE 1
#define OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE 1

// Security
#define OPENTHREAD_CONFIG_ECDSA_ENABLE 1
#define OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE 0

// Network data
#define OPENTHREAD_CONFIG_BORDER_ROUTING_ENABLE 0
#define OPENTHREAD_CONFIG_IP6_SLAAC_ENABLE 1

// Logging (reduced for memory)
#define OPENTHREAD_CONFIG_LOG_LEVEL OT_LOG_LEVEL_WARN
#define OPENTHREAD_CONFIG_LOG_API 0
#define OPENTHREAD_CONFIG_LOG_MLE 0
#define OPENTHREAD_CONFIG_LOG_ARP 0
#define OPENTHREAD_CONFIG_LOG_NETDATA 0
#define OPENTHREAD_CONFIG_LOG_ICMP 0
#define OPENTHREAD_CONFIG_LOG_IP6 0
#define OPENTHREAD_CONFIG_LOG_MAC 0
#define OPENTHREAD_CONFIG_LOG_MEM 0
#define OPENTHREAD_CONFIG_LOG_PKT_DUMP 0
#define OPENTHREAD_CONFIG_LOG_NETDIAG 0